### ISSUE TITLE
error during write data

### ISSUE THREAD

**Issue by almas123** [AlexeyPanchenko/printerservice#7]
hello, i am getting  PrintFailedException(message=Error during write data)
09-12 15:07:02.447 26524-26524/com.example.print_task W/System.err:     at ru.alexeyp.printerservice.connectors.PrinterConnector$print$1.subscribe(PrinterConnector.kt:28)
09-12 15:07:02.447 26524-26524/com.example.print_task W/System.err:     at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
09-12 15:07:02.447 26524-26524/com.example.print_task W/System.err:     at io.reactivex.Single.subscribe(Single.java:3313)
09-12 15:07:02.447 26524-26524/com.example.print_task W/System.err:     at io.reactivex.internal.operators.single.SingleTimeout.subscribeActual(SingleTimeout.java:53)
Some ideas?

**Comment by talhamughal10** [comment]
@almas123  Hi did you found printer discovery using this API?

**Comment by almas123** [comment]
> @almas123 Hi did you found printer discovery using this API?

hello,yes it is working , but file print does not work ,u need to print a simple text ,or convert ur file to PDL format it is big problem)
